apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app-deployment
  labels:
    app: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: omarrouby/lab-app-python
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: lab-app-service
spec:
  selector:
    app: lab-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
